output:
  format: json

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - dogsled
    - goprintffuncname
    - lll

    # FIXME I want this but our codebase doesn't conform.    - whitespace
  disable-all: true
  fast: false

linters-settings:
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 120
    # Tab width in spaces.
    # Default: 1
    tab-width: 1

issues:
  exclude-use-default: false
  fix: false
